name: Run Cypress Tests

on:
  # push:
    # branches:
      # - main 
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
          record: true
          browser: chrome
          #spec: cypress\e2e\Settings\TC_S_07_SettingsGeneral.cy.js,cypress/e2e/TC_S_01_Registration.cy.js,cypress/e2e/Social-Security/TC_S_04_SampleScenario.cy.js,cypress/e2e/Social-Security/TC_S_05_QuestionnaireScenario.cy.js,cypress/e2e/Social-Security/TC_S_06_IncomeLayer.cy.js,cypress/e2e/Social-Security/TC_S_06_IncomeLayer_PopUpControl.cy.js,cypress/e2e/Social-Security/TC_S_06_IncomeLayer_On_Off.cy.js
      env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
